// <auto-generated />
using System;
using Backend.Database.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250515061920_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Casino"
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("JackpotAmount")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("WebUrl")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GameId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1,
                            ImageUrl = "https://assets.funnygames.dk/2/114572/100319/1024x1024/yatzy.webp",
                            JackpotAmount = 10000m,
                            Name = "Yatzy",
                            Status = true,
                            WebUrl = "yatzy"
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2,
                            ImageUrl = "https://cdn.prod.website-files.com/5ae2e7a18cb7532f0710bdfb/5e21d7084c5acfd2a75b5c0f_small.jpg",
                            JackpotAmount = 5000m,
                            Name = "Blackjack",
                            Status = true,
                            WebUrl = "dice"
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 2,
                            ImageUrl = "https://mediumrare.imgix.net/12c3bb0487e2239772248e61550a121ee20fe8400a63f386d08896d1122d1655?q=85",
                            JackpotAmount = 15000m,
                            Name = "Bombastic",
                            Status = true,
                            WebUrl = "bombastic"
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.GameHistory", b =>
                {
                    b.Property<Guid>("GameHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsJackpotWin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WasCashedOut")
                        .HasColumnType("bit");

                    b.Property<decimal>("WinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GameHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameHistories");

                    b.HasData(
                        new
                        {
                            GameHistoryId = new Guid("a5acd3cb-f6db-4b61-9fc4-f0e53897802b"),
                            BetAmount = 100m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            IsJackpotWin = false,
                            IsWin = true,
                            UserId = 1,
                            WasCashedOut = false,
                            WinAmount = 0m
                        },
                        new
                        {
                            GameHistoryId = new Guid("113ef4b5-d0fb-45ec-afe0-26ac1c4fbff9"),
                            BetAmount = 50m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            IsJackpotWin = false,
                            IsWin = false,
                            UserId = 2,
                            WasCashedOut = false,
                            WinAmount = 0m
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.Transactions", b =>
                {
                    b.Property<Guid>("TransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionsId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionsId = new Guid("d644fccf-0da4-4fa7-9e04-b24c8142fd20"),
                            Amount = 500,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = "In",
                            Type = "Deposit",
                            UserId = 1
                        },
                        new
                        {
                            TransactionsId = new Guid("0715b8d9-3e35-4552-a828-d1dc30cacea9"),
                            Amount = 300,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Direction = "Out",
                            Type = "Withdrawal",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExcludedUntil")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("NewsLetterIsSubscribed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100m,
                            BirthDate = new DateTime(1990, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "NiklasErEnMaskine@mail.com",
                            FirstName = "Niklas",
                            LastName = "Maskine",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$24M9E64PSxQt77wHpsEpG.w0.3TGYlI3F.miac4F/saLl7z4GUnrm",
                            PhoneNumber = 12345678,
                            Profit = 50m,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 75m,
                            BirthDate = new DateTime(1990, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            NewsLetterIsSubscribed = false,
                            Password = "$2a$11$nEb4RGybZAX75Dk4A3xA..v.3YDZ5N/znr0GscVi8Aarnh/EbMObm",
                            PhoneNumber = 87654321,
                            Profit = 33m,
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Balance = 100m,
                            BirthDate = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.jensen@example.com",
                            FirstName = "Anna",
                            LastName = "Jensen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$kfitXySD7XK2v2.OoKzRx.fLX3l/oO0yob6BRk7Xd4gNA9FgMheXq",
                            PhoneNumber = 11111111,
                            Profit = 20m,
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Balance = 150m,
                            BirthDate = new DateTime(1988, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mark.larsen@example.com",
                            FirstName = "Mark",
                            LastName = "Larsen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$5Hx4rGK5wKBcx0mU4a6CgOqraGQTsALVyx.7SLvzAfCfW1Xux9MMG",
                            PhoneNumber = 22222222,
                            Profit = 40m,
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            Balance = 200m,
                            BirthDate = new DateTime(1992, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.hansen@example.com",
                            FirstName = "Sara",
                            LastName = "Hansen",
                            NewsLetterIsSubscribed = false,
                            Password = "$2a$11$e96g1HTAV15C0bSEd.AqoukDugHKgLvlvLNP76ABXH4Ho31P3xAYG",
                            PhoneNumber = 33333333,
                            Profit = 30m,
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            Balance = 300m,
                            BirthDate = new DateTime(1985, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.madsen@example.com",
                            FirstName = "Peter",
                            LastName = "Madsen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$QuC0FLWfDkwR9BuqlE0HeOgFmdAa4mP1TMRqZqeo5oL4nJCrEc.WS",
                            PhoneNumber = 44444444,
                            Profit = 70m,
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            Balance = 120m,
                            BirthDate = new DateTime(1998, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.poulsen@example.com",
                            FirstName = "Laura",
                            LastName = "Poulsen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$h90EcasXD8Z69CDkBVc95Oa5JjKeAPDESR4tTLMCH29ZcU1SB9eEW",
                            PhoneNumber = 55555555,
                            Profit = 25m,
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Balance = 180m,
                            BirthDate = new DateTime(1982, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.christensen@example.com",
                            FirstName = "Thomas",
                            LastName = "Christensen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$IetRj7Ww57r2wsAUxmhqtu6bREpsud4gZczRIcO3w6NIFBWwcFRl.",
                            PhoneNumber = 66666666,
                            Profit = 60m,
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Balance = 220m,
                            BirthDate = new DateTime(1994, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.andersen@example.com",
                            FirstName = "Emma",
                            LastName = "Andersen",
                            NewsLetterIsSubscribed = true,
                            Password = "$2a$11$TuA1AdWnkeZbrOCCpNjtYO3VjRJo8INGAy8P1pM9Ex.YPHzKFkWEG",
                            PhoneNumber = 77777777,
                            Profit = 80m,
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Balance = 90m,
                            BirthDate = new DateTime(1989, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mikkel.olsen@example.com",
                            FirstName = "Mikkel",
                            LastName = "Olsen",
                            NewsLetterIsSubscribed = false,
                            Password = "$2a$11$S.0eXchqhNr/WjhF.17eIe2zlG2muX8RRxvSC1lKOkJkzej0g5V9K",
                            PhoneNumber = 88888888,
                            Profit = 10m,
                            Role = 0
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.Game", b =>
                {
                    b.HasOne("Backend.Database.Entities.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Database.Entities.GameHistory", b =>
                {
                    b.HasOne("Backend.Database.Entities.Game", "Game")
                        .WithMany("GameHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Entities.User", "User")
                        .WithMany("GameHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.Transactions", b =>
                {
                    b.HasOne("Backend.Database.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Backend.Database.Entities.Game", b =>
                {
                    b.Navigation("GameHistories");
                });

            modelBuilder.Entity("Backend.Database.Entities.User", b =>
                {
                    b.Navigation("GameHistories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
